<script setup lang="ts">
import { z } from 'zod'
import type { FormSubmitEvent } from '@nuxt/ui'
import { createAdminApi } from '~/api/admin-api'
import type { CollectionContent } from '../types/collection-search'

const props = defineProps<{
  mode: 'create' | 'edit' | 'view'
  collection?: CollectionContent
}>()

const emit = defineEmits<{ saved: [] }>()

const open = defineModel<boolean>('open', { default: false })

const schema = z.object({
  name: z.string().min(1, 'El nombre es requerido').max(100, 'Máximo 100 caracteres'),
  slug: z.string().min(1, 'El slug es requerido').max(100, 'Máximo 100 caracteres')
    .regex(/^[a-z0-9-]+$/, 'Solo letras minúsculas, números y guiones'),
  description: z.string().max(500, 'Máximo 500 caracteres').optional(),
  imageUrl: z.string().url('Ingresa una URL válida').optional().or(z.literal('')),
  active: z.boolean(),
  position: z.number({ error: 'Ingresa un número válido' }).int().min(1, 'La posición debe ser mayor a 0')
})

type Schema = z.output<typeof schema>

const form = reactive<Schema>({
  name: '',
  slug: '',
  description: '',
  imageUrl: '',
  active: true,
  position: 1
})

const isSaving = ref(false)
const isSlugAutoGenerated = ref(true)

watch(open, (val) => {
  if (val) {
    form.name = props.collection?.name ?? ''
    form.slug = props.collection?.slug ?? ''
    form.description = props.collection?.description ?? ''
    form.imageUrl = props.collection?.imageUrl ?? ''
    form.active = props.collection?.active ?? true
    form.position = props.collection?.position ?? 1
    isSlugAutoGenerated.value = !props.collection
  }
})

function toSlug(text: string): string {
  return text
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
}

watch(() => form.name, (name) => {
  if (isSlugAutoGenerated.value) form.slug = toSlug(name)
})

function onSlugInput() {
  isSlugAutoGenerated.value = false
}

const title = computed(() => ({
  create: 'Nueva colección',
  edit: 'Editar colección',
  view: 'Detalle de la colección'
}[props.mode]))

const isReadOnly = computed(() => props.mode === 'view')

async function onSubmit(event: FormSubmitEvent<Schema>) {
  try {
    isSaving.value = true
    const api = createAdminApi()
    const body = {
      name: event.data.name,
      slug: event.data.slug,
      description: event.data.description || null,
      imageUrl: event.data.imageUrl || null,
      active: event.data.active,
      position: event.data.position
    }
    if (props.mode === 'create') {
      await api('/collections', { method: 'POST', body })
    } else {
      await api(`/collections/${props.collection!.id}`, { method: 'PUT', body })
    }
    emit('saved')
    open.value = false
  } catch (error) {
    console.error(error)
  } finally {
    isSaving.value = false
  }
}
</script>

<template>
  <UModal
    v-model:open="open"
    :title="title"
    size="lg"
    :ui="{ footer: 'justify-end' }"
  >
    <template #body>
      <UForm
        :schema="!isReadOnly ? schema : undefined"
        :state="form"
        class="space-y-4"
        @submit="onSubmit"
      >
        <!-- Image preview (view mode) -->
        <div
          v-if="isReadOnly && form.imageUrl"
          class="w-full h-40 rounded-lg overflow-hidden border border-gray-200"
        >
          <img
            :src="form.imageUrl"
            :alt="form.name"
            class="w-full h-full object-cover"
          >
        </div>

        <div class="grid grid-cols-2 gap-4">
          <UFormField
            label="Nombre"
            name="name"
            :required="!isReadOnly"
            class="col-span-2"
          >
            <UInput
              v-model="form.name"
              placeholder="Ej. Verano 2025"
              class="w-full"
              :disabled="isReadOnly"
              autofocus
            />
          </UFormField>

          <UFormField
            label="Slug"
            name="slug"
            :required="!isReadOnly"
            class="col-span-2"
          >
            <UInput
              v-model="form.slug"
              placeholder="ej. verano-2025"
              class="w-full font-mono"
              :disabled="isReadOnly"
              @input="onSlugInput"
            />
          </UFormField>
        </div>

        <UFormField
          label="Descripción"
          name="description"
        >
          <UTextarea
            v-model="form.description"
            placeholder="Descripción breve de la colección..."
            :rows="3"
            class="w-full"
            :disabled="isReadOnly"
          />
        </UFormField>

        <UFormField
          label="URL de imagen"
          name="imageUrl"
          hint="URL pública de la imagen de portada"
        >
          <UInput
            v-model="form.imageUrl"
            placeholder="https://..."
            class="w-full"
            :disabled="isReadOnly"
          />
        </UFormField>

        <div class="grid grid-cols-2 gap-4">
          <UFormField
            label="Posición"
            name="position"
            :required="!isReadOnly"
          >
            <UInputNumber
              v-model="form.position"
              :min="1"
              :step="1"
              class="w-full"
              :disabled="isReadOnly"
            />
          </UFormField>

          <UFormField
            label="Estado"
            name="active"
          >
            <div class="flex items-center gap-2 h-8">
              <USwitch
                v-model="form.active"
                :disabled="isReadOnly"
              />
              <span class="text-sm text-gray-600">
                {{ form.active ? 'Activa' : 'Inactiva' }}
              </span>
            </div>
          </UFormField>
        </div>

        <div
          v-if="!isReadOnly"
          class="flex justify-end gap-2 pt-1"
        >
          <UButton
            color="neutral"
            variant="outline"
            type="button"
            @click="open = false"
          >
            Cancelar
          </UButton>
          <UButton
            type="submit"
            :loading="isSaving"
          >
            {{ mode === 'create' ? 'Crear colección' : 'Guardar cambios' }}
          </UButton>
        </div>

        <div
          v-else
          class="flex justify-end pt-1"
        >
          <UButton
            color="neutral"
            variant="outline"
            @click="open = false"
          >
            Cerrar
          </UButton>
        </div>
      </UForm>
    </template>
  </UModal>
</template>
