<script setup lang="ts">
import { collectionSchema } from '../schemas/collection.schema'
import { useCollectionForm } from '../composables/useCollectionForm'

const { form, wordCount } = useCollectionForm()

const isSlugAutoGenerated = ref(true)

function toSlug(text: string): string {
  return text
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
}

watch(() => form.name, (name) => {
  if (isSlugAutoGenerated.value) form.slug = toSlug(name)
})

function onSlugInput() {
  isSlugAutoGenerated.value = false
}

const toolbarItems = [
  [
    {
      label: 'Párrafo',
      trailingIcon: 'i-lucide-chevron-down',
      items: [[
        { kind: 'paragraph', label: 'Párrafo' },
        { kind: 'heading', level: 1, label: 'Encabezado 1' },
        { kind: 'heading', level: 2, label: 'Encabezado 2' },
        { kind: 'heading', level: 3, label: 'Encabezado 3' },
        { kind: 'heading', level: 4, label: 'Encabezado 4' }
      ]]
    }
  ],
  [
    { kind: 'mark', mark: 'bold', icon: 'i-lucide-bold', tooltip: { text: 'Negrita' } },
    { kind: 'mark', mark: 'italic', icon: 'i-lucide-italic', tooltip: { text: 'Cursiva' } },
    { kind: 'mark', mark: 'underline', icon: 'i-lucide-underline', tooltip: { text: 'Subrayado' } }
  ],
  [
    { kind: 'bulletList', icon: 'i-lucide-list', tooltip: { text: 'Lista con viñetas' } },
    { kind: 'orderedList', icon: 'i-lucide-list-ordered', tooltip: { text: 'Lista numerada' } }
  ],
  [
    { kind: 'link', icon: 'i-lucide-link', tooltip: { text: 'Enlace' } }
  ]
]
</script>

<template>
  <div class="p-6 border border-[#ececed] rounded-xl bg-white">
    <div class="mb-5">
      <h3 class="font-semibold text-base">
        Información general
      </h3>
      <p class="text-sm text-gray-500 mt-0.5">
        Datos principales de la colección.
      </p>
    </div>

    <UForm
      :schema="collectionSchema"
      :state="form"
      class="space-y-5"
    >
      <div class="grid grid-cols-2 gap-4">
        <UFormField
          label="Título de la colección"
          name="name"
          class="w-full"
        >
          <UInput
            v-model="form.name"
            placeholder="Ej. Verano 2025"
            class="w-full"
          />
        </UFormField>

        <UFormField
          label="Slug (identificador)"
          name="slug"
          class="w-full"
        >
          <UInput
            v-model="form.slug"
            placeholder="ej. verano-2025"
            class="w-full font-mono"
            @input="onSlugInput"
          />
        </UFormField>
      </div>

      <UFormField
        label="Posición"
        name="position"
        class="w-40"
        hint="Orden de aparición en el catálogo"
      >
        <UInputNumber
          v-model="form.position"
          :min="1"
          :step="1"
          class="w-full"
        />
      </UFormField>

      <UFormField
        label="Descripción"
        name="description"
        class="w-full"
      >
        <div class="relative w-full">
          <UEditor
            v-model="form.description"
            content-type="json"
            placeholder="Escribe la descripción de la colección..."
            :starter-kit="{
              blockquote: false,
              heading: { levels: [1, 2, 3, 4] },
              dropcursor: { color: 'var(--ui-primary)', width: 2 },
              link: { openOnClick: false }
            }"
            class="w-full border border-[#cad5e2] rounded-md h-64"
          >
            <template #default="{ editor }">
              <UEditorToolbar
                :editor="editor"
                :items="toolbarItems"
              />
            </template>
          </UEditor>
          <span class="absolute bottom-2 right-3 text-xs text-gray-400 pointer-events-none select-none">
            {{ wordCount }} palabras
          </span>
        </div>
      </UFormField>
    </UForm>
  </div>
</template>
