<script setup lang="ts">
import { Cropper } from 'vue-advanced-cropper'
import 'vue-advanced-cropper/dist/style.css'
import { useFileDialog } from '@vueuse/core'
import type { CollectionContent } from '../types/collection-search'
import { useUpdateCollection } from '../composables/useUpdateCollection'

const props = defineProps<{
  collection?: CollectionContent
}>()

const open = defineModel<boolean>('open', { default: false })

const emit = defineEmits<{
  saved: []
}>()

const { updateCollection, isSaving, error: saveError } = useUpdateCollection()

const tabItems = [
  { label: 'Información básica', icon: 'i-lucide-info', slot: 'info' as const },
  { label: 'Multimedia', icon: 'i-lucide-image', slot: 'media' as const }
]

// ─── Form state ─────────────────────────────────────────────────────────────────
const name = ref('')
const slug = ref('')
const description = ref('')
const position = ref(1)
const active = ref(true)

const isSlugAutoGenerated = ref(false)

function toSlug(text: string): string {
  return text
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
}

watch(name, (val) => {
  if (isSlugAutoGenerated.value) slug.value = toSlug(val)
})

function onSlugInput() {
  isSlugAutoGenerated.value = false
}

// ─── Imagen ───────────────────────────────────────────────────────────────────
const imageBlob = ref<Blob | null>(null)
const imagePreview = ref<string>('')
const sourceObjectUrl = ref<string | null>(null)
const previewObjectUrl = ref<string | null>(null)
const imageError = ref('')

function revokeSource() {
  if (sourceObjectUrl.value) {
    URL.revokeObjectURL(sourceObjectUrl.value)
    sourceObjectUrl.value = null
  }
}

function revokePreview() {
  if (previewObjectUrl.value) {
    URL.revokeObjectURL(previewObjectUrl.value)
    previewObjectUrl.value = null
  }
}

function resetForm() {
  const c = props.collection
  name.value = c?.name ?? ''
  slug.value = c?.slug ?? ''
  description.value = c?.description ?? ''
  position.value = c?.position ?? 1
  active.value = c?.active ?? true
  isSlugAutoGenerated.value = false
  revokeSource()
  revokePreview()
  imageBlob.value = null
  imagePreview.value = c?.imageUrl ?? ''
  imageError.value = ''
}

watch(open, (isOpen) => {
  if (isOpen) resetForm()
})

// ─── Selección + recorte de imagen ──────────────────────────────────────────────
const cropperRef = ref()
const cropperSrc = ref('')
const showCropperModal = ref(false)

const { open: openFileDialog, onChange: onFileChange } = useFileDialog({
  accept: 'image/jpeg,image/png,image/webp',
  multiple: false
})

onFileChange((files) => {
  const file = files?.[0]
  if (!file) return
  if (file.size > 2 * 1024 * 1024) {
    imageError.value = 'La imagen supera el máximo de 2MB.'
    return
  }
  imageError.value = ''
  revokeSource()
  const url = URL.createObjectURL(file)
  sourceObjectUrl.value = url
  cropperSrc.value = url
  showCropperModal.value = true
})

function editCurrentImage() {
  if (!imagePreview.value) {
    openFileDialog()
    return
  }
  cropperSrc.value = imagePreview.value
  showCropperModal.value = true
}

function applyCrop() {
  if (!cropperRef.value) return
  const { canvas } = cropperRef.value.getResult()
  canvas.toBlob((blob: Blob | null) => {
    if (!blob) return
    revokePreview()
    const url = URL.createObjectURL(blob)
    previewObjectUrl.value = url
    imageBlob.value = blob
    imagePreview.value = url
    showCropperModal.value = false
  }, 'image/jpeg', 0.92)
}

function rotate(angle: number) {
  cropperRef.value?.rotate(angle)
}
function flipX() {
  cropperRef.value?.flip(true, false)
}
function flipY() {
  cropperRef.value?.flip(false, true)
}

onUnmounted(() => {
  revokeSource()
  revokePreview()
})

// ─── Guardado ───────────────────────────────────────────────────────────────────
async function onSave() {
  if (!props.collection) return

  const data = {
    name: name.value,
    slug: slug.value,
    description: description.value || null,
    active: active.value,
    position: position.value
  }

  const formData = new FormData()
  formData.append('data', new Blob([JSON.stringify(data)], { type: 'application/json' }))
  if (imageBlob.value) formData.append('image', imageBlob.value, 'collection.jpg')

  const result = await updateCollection(props.collection.id, formData)
  if (result) {
    emit('saved')
    open.value = false
  }
}
</script>

<template>
  <USlideover
    v-model:open="open"
    title="Editar colección"
    :ui="{ content: 'max-w-xl' }"
  >
    <template #body>
      <UTabs
        :items="tabItems"
        class="w-full"
      >
        <!-- Información básica -->
        <template #info>
          <div class="space-y-6 pt-4">
            <div class="grid grid-cols-2 gap-4">
              <UFormField
                label="Nombre"
                class="col-span-2"
              >
                <UInput
                  v-model="name"
                  placeholder="Ej. Verano 2025"
                  class="w-full"
                />
              </UFormField>

              <UFormField
                label="Slug"
                class="col-span-2"
              >
                <UInput
                  v-model="slug"
                  placeholder="ej. verano-2025"
                  class="w-full font-mono"
                  @input="onSlugInput"
                />
              </UFormField>
            </div>

            <UFormField label="Descripción">
              <UTextarea
                v-model="description"
                placeholder="Descripción breve de la colección..."
                :rows="3"
                class="w-full"
              />
            </UFormField>

            <div class="grid grid-cols-2 gap-4">
              <UFormField label="Posición">
                <UInputNumber
                  v-model="position"
                  :min="1"
                  :step="1"
                  class="w-full"
                />
              </UFormField>
            </div>

            <!-- Estado -->
            <div class="flex items-center justify-between pt-2 border-t border-gray-100">
              <div>
                <p class="text-sm font-medium text-gray-700">
                  Colección activa
                </p>
                <p class="text-xs text-gray-500">
                  Las colecciones inactivas no se muestran en la tienda.
                </p>
              </div>
              <USwitch v-model="active" />
            </div>
          </div>
        </template>

        <!-- Multimedia -->
        <template #media>
          <div class="space-y-3 pt-4">
            <p class="text-sm font-semibold text-gray-700">
              Imagen de portada
            </p>
            <p class="text-xs text-gray-500">
              Selecciona y recorta la imagen. Si no eliges una nueva, se conserva la actual.
            </p>

            <div class="relative group w-full aspect-video">
              <template v-if="imagePreview">
                <img
                  :src="imagePreview"
                  class="w-full h-full rounded-lg object-cover border border-gray-200"
                >
                <div class="absolute inset-0 rounded-lg bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2">
                  <button
                    type="button"
                    class="w-9 h-9 rounded-full bg-white/90 hover:bg-white flex items-center justify-center"
                    title="Editar imagen"
                    @click="editCurrentImage"
                  >
                    <UIcon
                      name="i-lucide-pencil"
                      class="w-4 h-4 text-gray-700"
                    />
                  </button>
                  <button
                    type="button"
                    class="w-9 h-9 rounded-full bg-white/90 hover:bg-white flex items-center justify-center"
                    title="Volver a seleccionar"
                    @click="openFileDialog()"
                  >
                    <UIcon
                      name="i-lucide-refresh-cw"
                      class="w-4 h-4 text-gray-700"
                    />
                  </button>
                </div>
              </template>
              <button
                v-else
                type="button"
                class="w-full aspect-video rounded-lg border-2 border-dashed border-gray-200 hover:border-primary transition-colors flex flex-col items-center justify-center gap-1 cursor-pointer"
                @click="openFileDialog()"
              >
                <UIcon
                  name="i-lucide-image-plus"
                  class="w-7 h-7 text-gray-300"
                />
                <span class="text-xs text-gray-400">Subir imagen</span>
              </button>
            </div>

            <p
              v-if="imageError"
              class="text-xs text-red-500"
            >
              {{ imageError }}
            </p>
          </div>
        </template>
      </UTabs>
    </template>

    <template #footer="{ close }">
      <div class="flex items-center justify-end gap-3 w-full">
        <p
          v-if="saveError"
          class="text-xs text-red-500 mr-auto"
        >
          {{ saveError }}
        </p>
        <UButton
          color="neutral"
          variant="ghost"
          @click="close"
        >
          Cancelar
        </UButton>
        <UButton
          color="primary"
          :loading="isSaving"
          @click="onSave"
        >
          Guardar cambios
        </UButton>
      </div>
    </template>
  </USlideover>

  <!-- Editor de imagen (hermano del slideover para apilarse por encima) -->
  <UModal
    v-model:open="showCropperModal"
    title="Editar imagen de portada"
    size="xl"
    :ui="{ overlay: 'z-[60]', content: 'z-[60]', footer: 'justify-end' }"
  >
    <template #body>
      <Cropper
        ref="cropperRef"
        class="h-96 w-full rounded-lg overflow-hidden bg-gray-900"
        :src="cropperSrc"
      />
      <div class="flex items-center gap-2 mt-4">
        <UButton
          color="neutral"
          variant="outline"
          size="sm"
          icon="i-lucide-rotate-ccw"
          @click="rotate(-90)"
        >
          Rotar izq.
        </UButton>
        <UButton
          color="neutral"
          variant="outline"
          size="sm"
          icon="i-lucide-rotate-cw"
          @click="rotate(90)"
        >
          Rotar der.
        </UButton>
        <UButton
          color="neutral"
          variant="outline"
          size="sm"
          icon="i-lucide-flip-horizontal-2"
          @click="flipX"
        >
          Voltear H
        </UButton>
        <UButton
          color="neutral"
          variant="outline"
          size="sm"
          icon="i-lucide-flip-vertical-2"
          @click="flipY"
        >
          Voltear V
        </UButton>
      </div>
    </template>
    <template #footer>
      <UButton
        color="neutral"
        variant="outline"
        @click="showCropperModal = false"
      >
        Cancelar
      </UButton>
      <UButton @click="applyCrop">
        Aplicar cambios
      </UButton>
    </template>
  </UModal>
</template>
